# General Jekyll Config
pygments: true
url: http://ericmitz.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
permalink: :title/
paginate: 10
excerpt_separator: <!--more-->
markdown: redcarpet

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: mitzimoto
    twitter: ericmitz
    hacker_news: MitziMoto
    linkedin: ericmitz
    #stackoverflow: 'http://stackoverflow.com/users/1713278/mitzimoto'
    gplus: 'https://plus.google.com/103836655075677405080/posts'

  # "Hi, I'm _______"
  name: Eric Mitz
  email: eric@ericmitz.com
  tagline: "weak opinions, strongly held"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
